//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectionTest.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConnectionTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Hello! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check connectable IPs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrCheckIPs {
            get {
                return ResourceManager.GetString("StrCheckIPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrCon {
            get {
                return ResourceManager.GetString("StrCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Destination IP address に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrDestIP {
            get {
                return ResourceManager.GetString("StrDestIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set DHCP to ON に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrDHCP {
            get {
                return ResourceManager.GetString("StrDHCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Network status (ipconfig) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrIpconfig {
            get {
                return ResourceManager.GetString("StrIpconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   My gateway に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrMyGateway {
            get {
                return ResourceManager.GetString("StrMyGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   My IP address に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrMyIP {
            get {
                return ResourceManager.GetString("StrMyIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   My subnet mask に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrMySubnetMask {
            get {
                return ResourceManager.GetString("StrMySubnetMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Network Adapter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrNIC {
            get {
                return ResourceManager.GetString("StrNIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Connected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrNotCon {
            get {
                return ResourceManager.GetString("StrNotCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection check (ping) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrPing {
            get {
                return ResourceManager.GetString("StrPing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ping timeout (ms) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrPingTimeout {
            get {
                return ResourceManager.GetString("StrPingTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrPort {
            get {
                return ResourceManager.GetString("StrPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check port (PortQry) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrPortQry {
            get {
                return ResourceManager.GetString("StrPortQry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rewrite the “Network and Sharing Center” setting in the “Control Panel”. Is it OK? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrQuestion {
            get {
                return ResourceManager.GetString("StrQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processing may take a few minutes. Do you want to process it? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrQuestionTwo {
            get {
                return ResourceManager.GetString("StrQuestionTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reacquire IP に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrReIP {
            get {
                return ResourceManager.GetString("StrReIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The following IP addresses have been successfully pinged. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrResPingAll {
            get {
                return ResourceManager.GetString("StrResPingAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change to the above に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StrSetToAbove {
            get {
                return ResourceManager.GetString("StrSetToAbove", resourceCulture);
            }
        }
    }
}
